library(pcaGoPromoter)
library(ellipse)
library(tidyr)
library(dplyr)
library(corrplot)
library(ggplot2)
library(reshape2)
library(RCurl)
library(mlbench)
library(caret)
library("e1071")
library(randomForest)
library(RCurl)
library(mlbench)
library(caret)
library("e1071")
library(randomForest)
library(ROCR)
library("pROC")
library("PRROC")

read.table("tair10_CO_training_data_norm.txt",header=T)->CO
CO$class <- ifelse(CO$class ==0, 'Random desert', 'COs')

pcaOutput <- pca(t(CO[,-ncol(CO)]), printDropped = FALSE, scale = T, center = T)
pcaOutput2 <- as.data.frame(pcaOutput$scores)
pcaOutput2$groups <- CO$class
centroids <- aggregate(cbind(PC1, PC2) ~ groups, pcaOutput2, mean)
conf.rgn  <- do.call(rbind, lapply(unique(pcaOutput2$groups), function(t) data.frame(groups = as.character(t),ellipse(cov(pcaOutput2[pcaOutput2$groups == t, 1:2]), centre = as.matrix(centroids[centroids$groups == t, 2:3]),level = 0.95), stringsAsFactors = FALSE)))
ggplot(data = pcaOutput2, aes(x = PC1, y = PC2, group = groups, color = groups)) + geom_polygon(data = conf.rgn,  alpha = 0.2) + geom_point(aes(colour = factor(groups))) +labs(color = "", fill = "",x = paste0("PC1: ", round(pcaOutput$pov[1], digits = 2) * 100, "% variance"),y = paste0("PC2: ", round(pcaOutput$pov[2], digits = 2) * 100, "% variance"))+scale_color_manual(breaks = c("COs","Random desert"), values=c("red", "green"))
